---
- name: Installing Nginx
  package:
    name: nginx
    state: latest
  tags:
    - docker
    - vagrant

- name: Enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - vagrant

# vim:sw=2:ts=2:et:
