---
- name: Installing Apache and PHP packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_ssl
    - php
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mysql
    - php-xml
    - php-xmlrpc

- name: Enable Apache service
  service:
    name: httpd
    state: started
    enabled: yes

# vim:sw=2:ts=2:et:
