---
- name: Install Wordpress packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mariadb-server
    - mod_ssl
    - php
    - php-curl
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mysql
    - php-xml
    - php-xmlrpc

- name: Enable Wordpress services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - mariadb

# vim:sw=2:ts=2:et:
