---
# tasks file for tchellomello.php
- name: Installing PHP packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - php
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mysql
    - php-xml
    - php-xmlrpc
  notify: restart_apache


# vim:sw=2:ts=2:et:
